name: Build MAUI Windows Project
on:
  workflow_dispatch:
  
env:
  PROJECT_PATH: "NerdNewsNavigator2/NerdNewsNavigator2.csproj"
  NUGETCONFIG_PATH: "nuget.config"
 
jobs:
   # ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
 maui-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # For WinUI builds
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Generate version number using date and run number
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "::set-output name=APP_VERSION::$ver"
    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      shell: pwsh
      run: dotnet restore ${{ env.PROJECT_PATH }} --configfile ${{ env.NUGETCONFIG_PATH }}

    - name: Build Maui WinUI project
      shell: pwsh
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=false
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./**/NerdNews*.msix
        
# ********************************* #
# >>>>>>> Build Release <<<<<<< #
# ********************************* #

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./**/*/NerdNews*.msix
