on: push

# This action only need a single permission in order to autoformat the code.
permissions:
  contents: read
  
jobs:
  autoformat-code:
    name: code format check
    runs-on: ubuntu-latest

    steps:
    - name: 'Autoformat'
      uses: rolfbjarne/autoformat@v0.2
      with:
        projects: "NerdNewsNavigator2.sln"
