name: Build

on:
  workflow_dispatch:

env:
  PROJECT_PATH: "NerdNewsNavigator2/NerdNewsNavigator2.csproj"
  NUGETCONFIG_PATH: "nuget.config"

jobs: 
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Install workload
      run: dotnet workload install maui
    
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Restore NuGet packages
      shell: pwsh
      run: dotnet restore ${{ env.PROJECT_PATH }} --configfile ${{ env.NUGETCONFIG_PATH }}
    
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./**/*
        
# ********************************* #
# >>>>>>> Build Release <<<<<<< #
# ********************************* #

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./**/*/*Signed.apk
            ./**/*Nerd*.msix
