name: Build

on:
  workflow_dispatch:

jobs: 
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Install workload
      run: dotnet workload install maui-android
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./**/*
        
# ********************************* #
# >>>>>>> Build Release <<<<<<< #
# ********************************* #

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./**/*/*Signed.apk
            ./**/*Nerd*.msix
