name: Publish Android Build

on:
  workflow_dispatch:
   paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
permissions:
  contents: write

env:
  PROJECT_PATH: "NerdNewsNavigator2/NerdNewsNavigator2.csproj"
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
 
jobs:

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
 maui-android:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '11'
    
    - name: Decrypt GPG File
      run: |
        echo "${{ secrets.KEYSTOREFILE }}" > NerdNewsNavigator2.Keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTOREPASSWORD }}" --batch NerdNewsNavigator2.Keystore.asc > NerdNewsNavigator2.Keystore
       
    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      shell: pwsh
      run: |
         dotnet nuget add source --username ne0rrmatrix --password ${{ secrets.APIKEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ne0rrmatrix/index.json"
         dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build Maui Android project
      shell: pwsh
      run: |
         dotnet build ${{ env.PROJECT_PATH }} -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=NerdNewsNavigator2.Keystore -p:AndroidSigningKeyAlias=${{ secrets.KEYSTOREALIAS }} -p:AndroidSigningKeyPass=${{ secrets.KEYSTOREPASSWORD }} -p:AndroidSigningStorePass=${{ secrets.KEYSTOREPASSWORD }}
    
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          name: android-ci-build
          path: .\**\net8.0-android\publish\*Signed.apk
   
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: .\**\net8.0-android\publish\*Signed.apk
          tag_name: 1.9.1-pre
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

